language: elixir
elixir:
  - 1.8.1
otp_release:
  - 21.2
before_script:
  - MIX_ENV=test mix compile --warnings-as-errors
script:
  - mix format --check-formatted
  - mix coveralls.travis
sudo: required
dist: trusty
cache:
  directories:
    - _build
    - deps
